# Generated by Django 5.0.1 on 2025-07-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicsReviewApp', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='comment',
        ),
    ]
