# Generated by Django 5.0.1 on 2025-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicsReviewApp', '0004_rename_review_text_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for newsletter subscription', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is subscription active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
